### PR TITLE
Bug/fix existing bugs

### LINKED ISSUE #49: Fix Existing Known Bugs
Try to fix existing known bugs

- [x] Fix bugs for Auth Flow
- [x] Fix bugs Current Order page
- [x] Fix bugs for Menu Page
- [x] Fix bugs for History page
- [x] Fix bugs in Feedback Page
- [ ] Create useLocalStorage hooks and replace it with all localStorage manipulation
- [ ] Hide Settings and Accounts Tab

### PR DESCRIPTION
**Pull request by PhucMaii**

### CODE REVIEW

File: src/components/Accordion/OrderDetails/OnHoldOrderDetails.jsx [hunk 1]
```diff
@@ -0,0 +1,359 @@
...
+            </Box>
+          </AccordionSummaryFlexBox>
+        </AccordionSummary>
+        <AccordionDetailsStyled>
+          <Grid container>
+            <Grid item xs={12} sm={6} textAlign="center">
+              <Typography fontWeight="bold" variant="h4">
+                Order
+              </Typography>
+              {items.map((item, index) => {
```
Comment (pgambhirlangara) [inline src/components/Accordion/OrderDetails/OnHoldOrderDetails.jsx]: items.length > 0 &&

File: src/pages/Menu/MenuPage.jsx [hunk 2]
```diff
@@ -114,37 +117,27 @@ export default function MenuPage() {
...
-        newMenu.push(...doc.data().sections);
-        doc.data().sections.map((section) => {
-          newSections.push(section.name);
+      if(querySnapshot.size > 0) {
+        const newMenu = [];
+        const newSections = [];
+        querySnapshot.forEach((doc) => {
+          setDocId(doc.id);
+          newMenu.push(...doc.data().sections);
+          doc.data().sections.map((section) => {
```
Comment (pgambhirlangara) [inline src/pages/Menu/MenuPage.jsx]: for () {
  for () {
  }
}

right now its O (n ^2 ), can we do it in O(n)

File: src/pages/Menu/MenuPage.jsx [hunk 3]
```diff
@@ -163,6 +156,20 @@ export default function MenuPage() {
         await updateDoc(docRef, { sections: menuData });
       } catch (error) {
         console.log(error);
+        const restaurantRef = JSON.parse(
+          localStorage.getItem('current-user'),
+        ).docId;
+        // Convert sections array to be an array of objects with the name is the section item
+        console.log(sections);
```
Comment (pgambhirlangara) [inline src/pages/Menu/MenuPage.jsx]: please remove console

**Review by pgambhirlangara — APPROVED** [review]
