### PR TITLE
Refs #16: Flow of Login Signup Page

### LINKED ISSUE #16: Flow of Login Signup Page (Create Restaurant Page)
- Signin Page is now Signup page, so verify if anything is broken
- Verify if signin with google and signup is directly working.
- Once the user is created, save that information into localstorage, localstorage.setItem('user', { } )
- Then verify if the user is succesfully redirected to Create Restaurant Page
- From the Create Restaurant Page remove Email, Password and confirm password fields.
- Link Forgot Password as well.

### PR DESCRIPTION
**Pull request by PhucMaii**

### CODE REVIEW

File: src/App.jsx [hunk 1]
```diff
@@ -1,8 +1,9 @@
 import { BrowserRouter, Routes, Route } from "react-router-dom";
 import { ThemeProvider } from "@mui/material";
-import SigninPage from "./pages/Signin/SigninPage";
+import SigninPage from "./pages/ForgotPassword/Signin/SigninPage";
```
Comment (knowprabhjyot) [inline src/App.jsx]: Why the Signin in Page import is coming from Forgot Password

**Review by knowprabhjyot — APPROVED** [review]
